name: sampleapp1
description: "Flutter Adaptive And Responsive Sample App 1"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/app_ios_icon.png
    - assets/images/app_android_icon.png
    - assets/images/app_macos_icon.png
    - assets/images/app_windows_icon.png
    - assets/images/app_web_icon.png
    - assets/images/044.png
    - assets/images/2.0x/044.png
    - assets/images/3.0x/044.png
    - assets/images/4.0x/044.png
    - assets/images/5.0x/044.png
    - assets/images/6.0x/044.png
    - assets/images/7.0x/044.png
    - assets/images/8.0x/044.png

flutter_launcher_icons:
  android: true
  image_path_android: assets/images/app_android_icon.png

  ios: true
  image_path_ios: assets/images/app_ios_icon.png
  remove_alpha_ios: true

  web:
    generate: true
    image_path: assets/images/app_web_icon.png

  windows:
    generate: true
    image_path: assets/images/app_windows_icon.png

  macos:
    generate: true
    image_path: assets/images/app_macos_icon.png


















